### ISSUE TITLE
Text, icons, and buttons are a little too small when run on a physical iPhone or Android device

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#18]
Maybe this can be fixed by changing the viewport width

**Comment by domyen** [comment]
**Re: font-size**
We can adjust the font-size. At the moment the font-size for todo items aligns with the size you'd see with list-item lockups on popular apps like Twitter or Sunrise –check out the screenshot below. Let's bump it up a tad and see how that goes?

![font-small](https://cloud.githubusercontent.com/assets/263385/4427164/53c12ab0-45bc-11e4-8928-50f8ce90b00f.jpg)

**Re: icons**
We've ensured that the clickareas adhere to mobile interface guidelines,  so are you referring to visible size? The one that stands out as being smallish is the trash icon. Which icons are you thinking of?

**Comment by stubailo** [comment]
In my opinion almost all of the click targets in the app felt a little too small - maybe apps like Twitter do some trickery such that if you narrowly miss the button it works anyway?

Let's see what it's like with a slight increase.

**Comment by stubailo** [comment]
Also, while we're doing this can we make part you can tap on to close the sidebar a little thicker on mobile? I know you can also swipe now, but it would be great to support both interactions.

**Comment by domyen** [comment]
From our in-person discussion (correct me if I'm wrong @stubailo): 
1. We're fine with icon size, the issue came up due to the native status bar overlaid atop the app nav thereby reducing the clickarea size by 1/2. It will be fixed when we're able to create an allowance for the status bars –pending some Cordova work. 
2. Text is fine

Todo for Dom:
- [x] Bump up the icon-trash size
- [x] Make the visible content area when the menu is open wider

**Comment by zol** [comment]
Lgtm.
