### ISSUE TITLE
When you click/tap on the list title, the number of tasks in the list very conspicuously disappears

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#23]
Maybe we can move it to the left of the list title so it doesn't disappear so suddenly? Alternatively, we can make it more obvious that the list title has transformed into an input by changing the background color or something.

**Comment by domyen** [comment]
Animating between the two states can address the sudden change in state. 

@tmeasday 
Update from in-person meeting: Let's try a fade-in-out when the edit template is toggled to communicate state change. Revisit if it remains unclear.

**Comment by tmeasday** [comment]
Is this what you were thinking @dominicnguyen ? It's tricky to only fade the number because of the way that UI hooks work. We could also do it pretty easily with a CSS transition if we left both elements on the screen and hid one.

Also it feels a bit weird that we are now repeating the "fade" transition. I guess I can generalise it although `{{#momentum plugin='fade'}}` would make it simple :)

**Comment by domyen** [comment]
Thanks @tmeasday. This is a much smoother and communicative transition for the title and buttons. @stubailo check it out?

I prefer the UI appearing with Meteor instead of the more jquery-ish approach of loading hidden things and toggling them.

**Comment by stubailo** [comment]
Looks good!
