### ISSUE TITLE
Animation page changes via fade in/out

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/mdg-todos#26]

**Comment by tmeasday** [comment]
There's an issue that `_uihooks` don't trigger when change from list->list as the template isn't changing and so IR doesn't trigger a re-draw (just changes the data context).

@dgreensp I wonder if you have any ideas on how you could "force" a re-render in Blaze.

I implemented a proof-of-concept for it at one point in [momentum](https://github.com/percolatestudio/meteor-momentum/commit/315818d166e1bb64aae58685e9c7cbbac67b7b66) which you could use to attach a reactive function to a `{{momentum}}` block that would force it to redraw. Kind of clumsy though.

**Comment by dgreensp** [comment]
It's a hack, but you can `{{#each}}` over an array of one object that has an `_id`.

**Comment by tmeasday** [comment]
@dgreensp so that'll redraw whenever the `_id` changes but not if any other attribute changes? 

Neat trick. Should we include it in the app?

**Comment by dgreensp** [comment]
I think so, since it's the only way I can think of to achieve the right semantics.  On one level it makes perfect sense, though I don't think all readers will find it intuitive.

Here's a crack at a comment explaining it: "We use #each on an array of one item so that the "list" template is removed and a new copy is added when changing lists, which is important for animation purposes.  #each looks at the _id property of its items to know when to insert a new item and when to update an old one."

**Comment by domyen** [comment]
lgtm

**Comment by domyen** [comment]
@tmeasday we should add a background behind the right column to fix the easing between page to page
@stubailo
