### ISSUE TITLE
The list title input doesn't save the new title when it is unfocused

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#37]

**Comment by tmeasday** [comment]
I actually did this intentionally but I'm not sure what the desired behaviour was. @dominicnguyen ?

**Comment by stubailo** [comment]
My main concern is that this doesn't match how editing tasks works. When you edit the name of a task it is saved immediately and therefore stays when you unfocus the field.

**Comment by tmeasday** [comment]
Hmm. I'm not sure the interaction will be the same though because tasks don't have a cancel button.

Should it save as you type? Thinking about it more I think it has to save on blur at the least anyway.

**Comment by stubailo** [comment]
I think it would be reasonable to make it save as you type just like the
tasks do, and change the cancel button to 'done' or remove it altogether.

**Comment by domyen** [comment]
The two ways to 'save' your input are _return_ and _blur_. The way to 'cancel' and revert back to the previous state is the _cancel_. I'm good with this pattern (i.e., the current iteration per Tom's commit).

I prefer having a cancel button that resets users to the initial state if we have save-as-you-type to provide an avenue to escape the flow.

**Comment by stubailo** [comment]
> I prefer having a cancel button that resets users to the initial state if we have save-as-you-type to provide an avenue to escape the flow.

What's different about editing the tasks themselves?

**Comment by domyen** [comment]
Lists are more important than tasks. Actioning a list affects the entire group of tasks whether that's editing or deleting. The life cycle of a task is to be quickly made and discarded. Lists aren't as temporal;  changing something seemingly insignificant like a name changes the perception of all the tasks inside the list. 

We treat tasks and lists differently because they serve different purposes for users. I liken the close/cancel button with the delete confirmation.

**Comment by stubailo** [comment]
OK fair enough.

**Comment by tmeasday** [comment]
Ok, I think this is fixed then.
