### ISSUE TITLE
Disable sidebar hover highlight on mobile

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#38]
On mobile, when you are dragging around the list of lists in the sidebar, sometimes random ones highlight as white, which is probably the hover effect from desktop. Let's disable that hover effect on mobile.

**Comment by tmeasday** [comment]
@dominicnguyen are you happy to just disable it with a media query or do you want to detect if we are in Cordova somehow?

**Comment by domyen** [comment]
The Cordova solution seems like the better way to ensure that only mobile devices get this style change.

**Comment by tmeasday** [comment]
Right, perhaps I should have said it's going to be more complicated. The problem is still there in any touch device, e.g. iOS in Safari. So I'm not convinced it's the right call.

**Comment by domyen** [comment]
@tmeasday The reason I say Cordova –rather than media queries– is that there is reassurance of a touch device. Given the landscape of device widths (phone, tablet, phablet), setting media queries would result in many false positives. Media queries are great for layout, I'm more conservative when using them for interaction.

e.g., what is the breakpoint for no hover state? iphone6, 6plus, 5s, ipad portrait, galaxys5, galaxy note.

**Comment by stubailo** [comment]
I think for now disabling hover just in Cordova is fine. It's pretty reasonable that native app would have a better experience than mobile web.

**Comment by tmeasday** [comment]
@dominicnguyen I added a `cordova` class to the container. Go forth.

**Comment by domyen** [comment]
@zol can you confirm?

**Comment by zol** [comment]
Problem solved, gw D.
