### ISSUE TITLE
Tapping list title on iOS doesn't start editing or open keyboard

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#46]
You have to tap the list title twice to edit it.

**Comment by stubailo** [comment]
I think we might have closed this as not reproducible, but I have a video of it happening again.

**Comment by tmeasday** [comment]
Here's the previous issue: https://github.com/percolatestudio/mdg-todos/issues/36

**Comment by tmeasday** [comment]
@stubailo I tried in my sim and real iOS device and didn't see anything. One thing I did see was a bit of a delay when clicking the title immediately after app launch.

Can you post the video? Any ideas on a repro?

**Comment by stubailo** [comment]
https://www.youtube.com/watch?v=FdOq4x0y08g&list=UU-wTnYJcaomBJxLY-EvxGxw

**Comment by tmeasday** [comment]
Thanks @stubailo. So the page enters "editing" mode but the input isn't focussed. 

It looks like the logic here: https://github.com/percolatestudio/mdg-todos/blob/master/client/templates/lists-show.js#L37-L40 is wrong.

Reproduced on my iPad. I'm not sure if it happens on phones?

**Comment by tmeasday** [comment]
It's odd. `$('.js-edit-form input[type=text]').length` shows `1` at that point (the input is rendered and on the page). Not really sure why `.focus()` isn't working.

I'm seeing a fair bit of jankiness in general with my iPad. It's not updated to iOS 8 yet though, I'm not sure if maybe I should do that?. I can't tell if you are updated yet?

**Comment by stubailo** [comment]
Ideally, the app should work well in iOS7 and 8, since not everyone will be
updated to the new one.

**Comment by tmeasday** [comment]
A ha! Reproduced on an iOS7 iPhone. So somethings changed in focussing inputs on iOS8. Investigating.

**Comment by tmeasday** [comment]
Ok, I think this comment here explains what's going on: http://stackoverflow.com/a/26185118/670639

I tested in MobSaf directly on both phones and it's broken there to. So in iOS the _only_ place it works is Cordova/iOS8. 

The reason is that because we pass a callback into `afterFlush`, the browser sees the focus as being outside of the click handler[1]. As the SO answerer explains, the reason it works in Cordova/iOS8 is due to a new setting for iOS8 webview apps that allows non-click focussing.

A simple solution is to use an `Tracker.flush()` instead and force the flush outside of a timeout. Perhaps @dgreensp should check that this is OK.

[1] This is because afterFlush triggers a `setTimeout(0)`.
